---
- name: Copy Topbeat config file.
  template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
    mode: "0644"
    owner: root
    group: root
    validate: "/usr/bin/topbeat -configtest -c %s"
  notify: restart topbeat

- name: Start Topbeat service.
  service:
    name: topbeat
    state: running

